# Generated by Django 3.2 on 2023-06-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InflacionDeCanasta', '0002_alter_anio_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='id_Anio',
            field=models.ForeignKey(blank=True, db_column='id_Anio', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.anio'),
        ),
    ]
