# Generated by Django 3.2 on 2023-06-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InflacionDeCanasta', '0004_alter_producto_gramos_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anio',
            name='id_Producto',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='diferencia',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='id_Mes',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_Mes',
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_Canasta',
            field=models.ForeignKey(blank=True, db_column='id_CanaSta', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.canastabasica'),
        ),
        migrations.AddField(
            model_name='inflacion',
            name='id_Canasta',
            field=models.ForeignKey(blank=True, db_column='id_Canasta', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.canastabasica'),
        ),
        migrations.AddField(
            model_name='mes',
            name='id_Canasta',
            field=models.ForeignKey(blank=True, db_column='id_Canasta', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.canastabasica'),
        ),
        migrations.AddField(
            model_name='mes',
            name='id_Producto',
            field=models.ForeignKey(blank=True, db_column='id_Producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Anio',
            field=models.ForeignKey(blank=True, db_column='id_Anio', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.anio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Canasta',
            field=models.ForeignKey(blank=True, db_column='id_Canasta', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.canastabasica'),
        ),
        migrations.AlterField(
            model_name='inflacion',
            name='id_Gasto',
            field=models.ForeignKey(blank=True, db_column='id_Febrero', null=True, on_delete=django.db.models.deletion.PROTECT, to='InflacionDeCanasta.gasto'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='anio',
            table='anio',
        ),
        migrations.AlterModelTable(
            name='canastabasica',
            table='canastabasica',
        ),
        migrations.AlterModelTable(
            name='gasto',
            table='gasto',
        ),
        migrations.AlterModelTable(
            name='inflacion',
            table='inflacion',
        ),
        migrations.AlterModelTable(
            name='mes',
            table='mes',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
